### ISSUE TITLE
Update CXX code to use new layout for PCI device.

### ISSUE THREAD

**Issue by shibedrill** [gibsonpil/libpci-rs#14] opened 2024-03-12 01:52 UTC
I changed PciDeviceHardware to take an address field of type Option<PciDeviceAddress>. Two things need to be done here.
1: It has to be changed to a Result, so the appropriate error (unavailable on the platform, permission denied, etc) can be included in the field.
2: The CXX backends need to be updated to include definitions of PciDeviceAddress.

**Comment by shibedrill** [comment] 2024-03-12 01:57
This also goes hand-in-hand with my proposed removal of the field availability system (as it is right now). Instead of returning a zeroed structure, we should use constants in the PCI module to define whether each field is available, and they can be configured depending on the platform compilation.

**Comment by shibedrill** [comment] 2024-03-12 02:01
Revision to the previous comment:
The field availability system can be made simpler by just privatizing fallible fields and only providing Getters if the platform supports them.

**Comment by gibsonpil** [comment] 2024-03-14 19:43
> This also goes hand-in-hand with my proposed removal of the field availability system (as it is right now). Instead of returning a zeroed structure, we should use constants in the PCI module to define whether each field is available, and they can be configured depending on the platform compilation.

The problem with doing that is that permission issues are very much environment dependent. Sometimes certain fields will be available whilst others aren't not purely based on platform, but also based on the user permission level.

>Revision to the previous comment:
The field availability system can be made simpler by just privatizing fallible fields and only providing Getters if the platform supports them.

Maybe. The issue is having each backend communicate which fields are and aren't available and for what reason succinctly. Ideally we figure out a way to do it without adding hundreds of lines of boilerplate code in.

Notwithstanding all of that, I've updated the CXX code to adapt the layout on the C++ side to the one on the Rust side. Though std::optional is a thing, moving it over to Rust isn't currently possible (at least not easily possible), so I've simply had each field set to zero when non-existent, which the Rust side then uses to determine whether or not the address structure should be Some or None.

**Closed by gibsonpil** 2024-03-14 19:43 UTC
